version: '3'
services:
  gagarin-db:
    container_name: "gagarin-db"
    image: "gagarin/db"
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql:Z
    ports:
      - "${MYSQL_PORT}:3306"
  gagarin-raketa:
    container_name: "gagarin-raketa"
    image: "gagarin/raketa"
    build:
      context: ./raketa
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_PORT=${MYSQL_PORT}
        - LARAVEL_DOMAIN=${LARAVEL_DOMAIN}
        - LARAVEL_PORT=${LARAVEL_PORT}
    ports:
      - "${LARAVEL_PORT}:80"
      - "${LARAVEL_PORT_HTTPS}:443"
    depends_on:
      - "gagarin-db"
  gagarin-app:
    container_name: "gagarin-app"
    image: "gagarin/app"
    build:
      context: ./gagarin
      args:
        - NODE_ENV=${NODE_ENV}
        - MDBVUE_PASSWORD=${MDBVUE_PASSWORD}
        - LARAVEL_DOMAIN=${LARAVEL_DOMAIN}
        - LARAVEL_PORT=${LARAVEL_PORT}
    ports:
      - "${APP_PORT}:80"
      - "${APP_PORT_HTTPS}:443"
    depends_on:
      - "gagarin-db"
      - "gagarin-raketa"
